apiVersion: harness.io/v1
kind: Resource
name: SYSID-07416 MongoDB (Dev)
identifier: sysid07416_mongo_dev
type: database
owner: group:account/DevX_Team
spec:
  system:
    - system:account/my_test_system
metadata:
  description: MongoDB instance for Fuse services - Dev environment
  tags:
    - mongodb
    - dev
