apiVersion: harness.io/v1
kind: Component
type: service
identifier: test_something_2
name: test_something_2
owner: user:kota.karthik@harness.io
spec:
  lifecycle: experimental
metadata:
  description: test
  annotations:
    backstage.io/techdocs-ref: dir:.
